### ISSUE TITLE
Feature Proposal: have a command to list all the service instances which have not yet completed

### ISSUE THREAD

**Issue by tszebeni** [meshcloud/unipipe-cli#8]
Feature Proposal: It would be nice to have a command to list all the service instances which have not yet been completed.
Inside a CI/CD pipeline watching the GIT repository for service instance definitions coming from marketplace, either for a create or update it is not trivial to find out that which are the only services which need to be reacted upon (imagine 3-4 services in marketplace but 100-200 service instances). As a workaround the CI/CD pipeline can look at commit message to find out latest service instance to trigger its automation but that is not perfect solution. It would be recommended to use heuristics on service instance definition files which handles even edge cases and probably the best place for it is the unipipe-cli here. The naive CI/CD which executes all the (probably terraform) steps for each service instances would be a bottle neck otherwise.

Please consider and recommend,
Thank you

**Comment by JohannesRudolph** [comment]
Hi @tszebeni. There are multiple ways we can figure this out (just scribbling the ideas here). Let me know which one you like best and think we should explore further.

**1) Look for an empty status**

New service instances typically have no status.yml file yet, meaning the CI/CD pipeline has yet not processed them.  The`unipipe list` command will show this as an empty status. 

```text
11:45 $ ./unipipe/unipipe.sh list test/osb-git/
id                                   service                   plan                              status    deleted
eed1df43-e63c-40ad-995e-e21068254ef9 Full Team Onboarding plan Azure DevOps                                true   
159440dd-652a-4e2b-916e-9cd4dde33c33 Azure VPC                 Azure VPC a Service (Teant Aware) succeeded false  
49c96fa5-46cc-4334-a718-378ceed2de81 Full Team Onboarding plan Azure DevOps                      succeeded false  
```

These can be filtered from the output via some bash trickery, e.g. awk but thinking of that it makes sense to add first party "filter expression" support to the `unipipe list` command, so the command would become `unipipe list --status="succeeded"` `unipipe list --status=""`.

**2) Transform and query git status**
This approach would be closer to the "idempotent" way of just transforming everything and executing all generated IaC, but still retaining some "incremental" process.
 
Idea: run all transforms and figure out what changed in the IAC via git 

```bash
git clone osb-repo

unipipe transform osb-repo --handlers=...js

cd osb-repo

# list added files (might need some tweaking)
git ls-files . --exclude-standard --others

#list modified files (e.g. because the handler emitted slightly different IaC)
git ls-files --modified

# todo: collect list of files from above, and execute the corresponding IaC

git add .
git commit -m "update..."
git push
```

**Comment by tszebeni** [comment]
Hi @JohannesRudolph, Thanks for the feedback.
Given the simplicity of the first approach it may fit our needs. Can we assume that an update on service instance request (e.g. change plan or parameters) will reset the previous status information?

Thanks again

**Comment by JohannesRudolph** [comment]
>  Can we assume that an update on service instance request (e.g. change plan or parameters) will reset the previous status information?

Good point. Updates on a service instance made by the unipipe service broker won't reset the instance's `status.yml` file... I've raised https://github.com/meshcloud/unipipe-service-broker/issues/22 to discuss this as from my PoV it seems sensible regardless of how we choose to facilitate the incremental service instance update scenario using unipipe-cli.

**Comment by felixzieger** [comment]
This has been implemented. For example the command `unipipe list --status="EMPTY" .` will list all service instances that do not have a status.

```
  Usage:   unipipe list <repo>
  Version: v0.6.0

  Description:

    Lists service instances status stored in a UniPipe OSB git repo.

  Options:

    -h, --help                      - Show this help.
    -p, --profile        [profile]  - include columns of context information according to the specified OSB API
                                    profile. Supported values are 'meshmarketplace' and 'cloudfoundry'. Ignored
                                    when '-o json' is set.
    -o, --output-format  [format]   - Output format. Supported formats are json and text.                          (Default: "text")
    --status             [status]   - Filters instances by status. Allowed values are 'in progress', 'succeeded',
                                    'failed' and 'EMPTY' (no status file present for this instance).
    --deleted            [deleted]  - Filters instances by deleted. Allowed values are 'true' and 'false'
 ```
